version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        container_name: slim-scafold
        restart: always
        image: danteay/php7-pgsql
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            APPNAME: SLIM_SCAFOLD
            ERROR_DETAILS: 'true'
            DATABASE_URL: postgres://postgres:1qaz2wsx@postgres:8081/test
            REDIS_URL: tcp://redis:6379
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
        links:
            - "postgres:db"
            - "redis:redis"

    postgres:
        image: postgres:10
        restart: always
        environment:
            POSTGRES_PASSWORD: 1qaz2wsx
            POSTGRES_USER: postgres
            POSTGRES_DB: test
        ports:
            - 8081:5432

    redis:
        image: redis
