version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        container_name: slim-scafold
        restart: always
        build:
            context: .
            dockerfile: dev.dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            APPNAME: slim-scafold
            ERROR_DETAILS: 'true'
        ports:
            - 8080:8080
        volumes:
            - .:/var/www

